spring.application.name=Ignite
app.jwt.expiration.ms=1800000
app.jwt.secret=b88361ed7ddf4fd879402d562f4838ad0f83605c74a0361e5847a8781a49ce68
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d810nfhj2pic73bfhigg-a:5432/ignite_database_652q}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ignite_database_652q_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kkhxiyyYP3BvQg4KB6DzArMqd4YAReun}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yousefabdallah031@gmail.com
spring.mail.password=zqav jyqw gcle hyiz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#logging.level.root=ERROR
#logging.level.org.hibernate.SQL=OFF
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
#logging.level.org.springframework=ERROR
#logging.level.org.springframework.boot=ERROR
#logging.level.org.apache.catalina.core=ERROR

server.tomcat.accesslog.enabled=false


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# Paymob Integration
# Paymob API base (used for all API calls)
paymob.api.base=https://accept.paymob.com/api


# Your Paymob API key (from dashboard)
paymob.api.key=ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRBNE9UQTJOU3dpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5DbGttR2ZFYlhFOWtHY0hPT0o3Mlc3SUxEVU5XT1VCVk5IN3hQZzAtNzByR0JUckUzZTA3NzlaMmV3bi1jQjRjRFhDQkhZSzBpOUVlRGJ3emtOY1dtUQ==

# Integration ID (linked to your payment method)
paymob.integration.id=5352652

# Iframe ID (from dashboard)
paymob.iframe.id=967648

# Optional: Webhook secret for verifying HMAC (if used)
paymob.webhook.secret=8BB7D9E3CAB9234DE7B9853DD96B3BFF
