spring.application.name=Ignite
app.jwt.expiration.ms=1800000
app.jwt.secret=${APP_JWT_SECRET}
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d810nfhj2pic73bfhigg-a:5432/ignite_database_652q}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ignite_database_652q_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false



spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#logging.level.root=ERROR
#logging.level.org.hibernate.SQL=OFF
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
#logging.level.org.springframework=ERROR
#logging.level.org.springframework.boot=ERROR
#logging.level.org.apache.catalina.core=ERROR

server.tomcat.accesslog.enabled=false


spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=8MB


# Paymob Integration
# Paymob API base (used for all API calls)
paymob.api.base=https://accept.paymob.com/api


# Paymob secrets (from dashboard)
paymob.api.key=${PAYMOB_API_KEY}
paymob.integration.id=${PAYMOB_INTEGRATION_ID}
paymob.iframe.id=${PAYMOB_IFRAME_ID}

# Optional: Webhook secret for verifying HMAC (if used)
paymob.webhook.secret=${PAYMOB_WEBHOOK_SECRET}
